Query data and update tables
Trust-007/vet-clinic pull request #2
Opened 2023-01-17 22:20 UTC by Trust-007

- Use database transactions.
- Modify and delete data in SQL.
- Prepare complex queries that answer analytical questions.

![Screenshot (50)](https://user-images.githubusercontent.com/72111684/213024828-8cacd4fe-4e63-4381-9ad7-12905af78cd9.png)
![Screenshot (51)](https://user-images.githubusercontent.com/72111684/213024833-d743d27d-01a3-4549-8c3b-ef2970c15221.png)
![Screenshot (42)](https://user-images.githubusercontent.com/72111684/213024835-9a0cdb2f-ad49-461b-836e-09ddf74f14f6.png)
![Screenshot (43)](https://user-images.githubusercontent.com/72111684/213024841-5f9fd357-fa1d-4fe9-960b-626239bfdb67.png)
![Screenshot (44)](https://user-images.githubusercontent.com/72111684/213024848-0e5aa14d-244f-44cc-bad5-0d0862da8973.png)
![Screenshot (45)](https://user-images.githubusercontent.com/72111684/213024854-525e6836-c8b4-48ad-807a-1f548246e29e.png)
![Screenshot (46)](https://user-images.githubusercontent.com/72111684/213024865-a14a7b93-8108-435c-88cc-5b61eed6ff4b.png)
![Screenshot (47)](https://user-images.githubusercontent.com/72111684/213024870-49b0972b-a20e-45ac-ba52-96d29527cf19.png)
![Screenshot (48)](https://user-images.githubusercontent.com/72111684/213024877-3513b71f-b2d5-467a-a2f0-eb4df4600dbd.png)
![Screenshot (49)](https://user-images.githubusercontent.com/72111684/213024888-17c93147-4ceb-4124-a5d2-b443a23d3ed3.png)

2023-01-17 23:15 UTC, mckent05 requested changes
Hi @Trust-007, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
- Please don't forget to update your PR with a screenshot of the changes you made 🙏 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 23:15 UTC, mckent05 commented on queries.sql
> +
- Please include a query to perform this `How many animals are there?`

2023-01-17 23:15 UTC, mckent05 commented on queries.sql
> +SELECT MAX(weight_kg), MIN(weight_kg) FROM animals;
- This query should get the minimum and max weight for each type of animal (GROUP_BY Species). Please fix this 🙏 
- Also please include a query to get `the average number of escape attempts per animal type of those born between 1990 and 2000?`

2023-01-18 14:38 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @Trust-007 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 14:39 UTC, merged